### ISSUE TITLE
RTS emits default VizInit rather than consuming ReplaySessionConfig to obtain step_count 

### ISSUE THREAD

**Issue by jedirv** [SCAII/Sky-RTS#11]
(on integ branch)

replay sends this is a final configuration gesture so that the backend can formulate a vizInit with step_count
```rust
ScaiiPacket {
            src: protos::Endpoint {
                endpoint: Some(Endpoint::Replay(ReplayEndpoint {})),
            },
            dest: protos::Endpoint {
                endpoint: Some(Endpoint::Backend(BackendEndpoint {})),
            },
            specific_msg: Some(SpecificMsg::ReplaySessionConfig(ReplaySessionConfig {
                step_count: steps,
            })),
        }
```

but backend complains with error:

```
received packet ScaiiPacket { src: Endpoint { endpoint: Some(Core(CoreEndpoint)) }, dest: Endpoint { endpoint: Some(Replay(ReplayEndpoint)) }, specific_msg: Some(Err(Error { description: "Invalid payload received in backend: ScaiiPacket { src: Endpoint { endpoint: Some(Replay(ReplayEndpoint)) }, dest: Endpoint { endpoint: Some(Backend(BackendEndpoint)) }, specific_msg: Some(ReplaySessionConfig(ReplaySessionConfig { step_count: 19 })) }", fatal: None, error_info: None })) }
```

grepping the code reveals that RTS is still just sending a default VizInit rather than consuming the ReplaySessionConfig message:
```
C:\Users\Jed Irvine\.scaii\git\Sky-RTS\backend>rg VizInit
src\engine\mod.rs
247:            // Build output (VizInit for clearing the screen; Viz for initial display)
261:                specific_msg: Some(protos::scaii_packet::SpecificMsg::VizInit(
262:                    protos::VizInit::default(),
111

**Comment by UserAB1236872** [comment]
What is step count?

**Comment by jedirv** [comment]
It's the number of steps in the game so that the UI can know how to dimension the timeline.

**Comment by UserAB1236872** [comment]
Why not make that a separate packet? That doesn't seem like the bakend's
job.

**Comment by jedirv** [comment]
I think our philosophy of protobuf message layout has evolved.  Initially I think we were trying to minimize the number of packet types, and so putting more fields in fewer packets.  I agree it doesn't make much sense for replay to pass that to backend to pass to UI.  It will require some changes in the Javascript side, but minimal.

I will:
- send the ReplaySessionConfig message (which has step_count) to the UI rather than backend.
- I will add a field to carry the vector of ExplanationPoints rather than having VizInit send that message
- generate new javascript protobuf files
- generate new python protobuf files

Change the UI to listen to the ReplaySessionConfig
