### ISSUE TITLE
step information not flowing

### ISSUE THREAD

**Issue by jedirv** [SCAII/Sky-RTS#14]
We have an oversight in play.  

UI needs to know the step.

Replay deduces the step by position in the list of ReplayActions, but doesn't have a way to communicate that to Rts.

I think the simplest, cleanest solution would be to add a step field to Action that is sent by Agent.

That way none of the intermediate mechanisms need to change - just adding the one-up in the Agent and pulling the value out of Action to put it into Viz.

Thoughts?

**Comment by jedirv** [comment]
Actually I think it makes more sense for Recorder to set the field before it stores the ReplayAction. That way we don't have to worry about the Agent's sense of step position and Replay's sense of step position getting out of sync somehow (like if an action is dropped somehow, even though unlikely).

**Comment by UserAB1236872** [comment]
Why not just make this a field of the RecorderStep or whatever then?

**Comment by UserAB1236872** [comment]
I'll be there soon, but I think that:

Receiving a VizInit should always set step to 0
Receiving a Viz should increment step by 1
There should be a message from the recorder than can set the step to an arbitrary value

Note that this means that explanation info should be a separate packet from Viz too, which is probably for the best anyway.

**Comment by jedirv** [comment]
I think debuggability favors an "in-band" signaling approach where all the metadata for the state flows together in one message (i.e. including the step number in Viz).  

Is there a particular reluctance in associating a step position to the Action by adding a field to it?  That seems the simplest to me.  

The explanation info flow needs to change  for sure - I'll put up another issue for that.

**Comment by UserAB1236872** [comment]
When it comes down to it, it's not a backend's job to communicate with the replay bar. The Replay binary is already managing rewinding and fast forwarding state, so it should just send a message. We already know messages flow in the exact order they're sent, so by calling the RTS' update function first you know for sure you can always send the step override after.

**Comment by UserAB1236872** [comment]
Also, it adds parsing complexity to the message and handling complexity to every potential backend. I have to either add another field to the RTS I always remember to check, or another argument to each function that could emit a `Viz`.

**Comment by jedirv** [comment]
I see. It still seems messy, but I see your points.  I'll make it so.

**Comment by jedirv** [comment]
I propose I make this change before we do any major refactoring on dev so Alan can see a working demo on Monday.

**Comment by jedirv** [comment]
I'll remove these two fields from Viz:

    optional ChartInfo chart = 2;
    optional uint32 step = 3;

...as I'll need to manage chart Info in a similar fashion to explanations

**Comment by jedirv** [comment]
We've decided that I will only send keyframes at the start or after rewind, since it's most likely that game state won't get out of sync.  

So, I will still record the serResponse with an associated action, but when replay reads it out, I will pull out the serResponse pkt out into a hash indexed by step number, then pull them out as needed upon rewind. That way we don't have the inefficiency of sending them so often.
