### ISSUE TITLE
file format for explanationPoints file

### ISSUE THREAD

**Issue by jedirv** [SCAII/Sky-RTS#18]
The format I used for recorder was to serialize the protobuf message into a byte array using the protobuf serialization.  Then I wrapped that byte array in a rust struct so that I could use the vanilla serde on it.  We can't do that in this case, and for this simpler "single type" list we don't really need to -  we can just wrap the explanationPoint vector in a new protobuf message like this:

ExplantationPoints {
   repeated ExplanationPoint  = 1;
} 

That way I just read in the file and use the protobuf deser on that to access the vector of EPs.  Sound good?

Jed

**Comment by UserAB1236872** [comment]
Okay, after thinking more, we can do this. It saves sending big data packets everywhere. However, can we make it part of the recorder rather than forcing the agent to save it? It would just make things easier in general. Just add an optional explanation encode as a field to whatever you're currently writing to file.

**Comment by jedirv** [comment]
I think so, but let's have a think through of pros and cons next time we are together.  One of my justification for separate files was to shield Magesh from dealing with protobufs, but that has as much to do with the fact that the bar chart message formats I put in play were organized around the notions of the particular bar chart library I was using.  Looking at them now I can't make sense of them without re-consulting the barchart library docs.  I wonder if there is a more intuitive and perhaps generic format that we could come up with that would make it easier to work with.  If we do that, then maybe the overall simplest thing would be to send the info along with the action to Recorder, but don't include it with the Actions sent to the game, and then all of it goes into one file, as originally planned.  There's definitely a simplicity win with not having to deal with multiple files, should we need to pass them around and such.  Anyway, let's discuss Monday.

**Comment by jedirv** [comment]
Decision will be to include ExplanationPoint in Action packets sent to recorder, but not the ones sent to the backend.  Then when recorder reads it, it will strip out the ExplanationPoint before forwarding the Action.

So we keep the single replay file design.

Reward/Chart info will become an optional field in Explanation Point.
